version: "3"
services:
  app:
    volumes:
      - /app
    container_name: temperature-challenge-charlie-docker-dev
    image: temperature-challenge-charlie-docker-dev
    build: 
      context: .
      target: dev
    ports:
      - 3000:3000