version: "3"
services:
  app:
    volumes:
      - /app
    container_name: temperature-challenge-charlie-docker-prod
    image: temperature-challenge-charlie-docker-prod
    build: 
      context: .
      target: prod
    ports:
      - 3000:3000